version: '3.8'
services:
  web:
    build: .
    restart: always

  nginx:
    depends_on:
      - web
    restart: always
    links:
      - web
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "4443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
